;<table className="projectPlanning">
  <thead>
    <tr>
      <th>Project</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Organic</td>
      <td>2.4</td>
      <td>1.05</td>
      <td>2.5</td>
      <td>0.38</td>
    </tr>
    <tr>
      <td>Semidetached</td>
      <td>3.0</td>
      <td>1.12</td>
      <td>2.5</td>
      <td>0.35</td>
    </tr>
    <tr>
      <td>Embedded</td>
      <td>2.4</td>
      <td>1.05</td>
      <td>2.5</td>
      <td>0.38</td>
    </tr>
  </tbody>
</table>
